### ISSUE TITLE
Error when making predictions using Independent() model with single dimensional latent space 

### ISSUE THREAD

**Issue by jgallowa07** [matsengrp/torchdms#169]
I trained some `Independent()` and `conditionalSequential()` models using the following [options](https://github.com/matsengrp/torchdms-experiments/blob/master/experiments/2022-05-18-calibrated-octet/option.json). 

I then loaded and and ran [this notebook](https://github.com/matsengrp/torchdms-experiments/blob/master/misc/ge/torchdms-model-eval-ge.ipynb) for model evaluation of global epistasis using octet data & held testing data. It seems doing the basic model prediction with `model(seq_to_binary(aa_seq))` function calling heuristic has raised the following error when using the independent models:

```
File ~/MatsenGroup/Projects/torchdms/torchdms/torchdms/model.py:104, in TorchdmsModel.forward(self, x, **kwargs)
     94 def forward(self, x: torch.Tensor, **kwargs) -> torch.Tensor:
     95     # pylint: disable=arguments-differ
     96     r"""data :math:`X` :math:`\rightarrow` output :math:`Y`.
     97 
     98     .. math::
   (...)
    102         x: input data tensor :math:`X`
    103     """
--> 104     return self.from_latent_to_output(self.to_latent(x, **kwargs), **kwargs)

File ~/MatsenGroup/Projects/torchdms/torchdms/torchdms/model.py:697, in Independent.to_latent(self, x, **kwargs)
    692 def to_latent(self, x: torch.Tensor, **kwargs) -> torch.Tensor:
    693     #print(f"model_bind to latent: {self.model_bind.to_latent(x)[None, :]}") 
    694     #print(f"model_stab to latent: {self.model_stab.to_latent(x)[None, :]}")
--> 697     return torch.cat(
    698         (self.model_bind.to_latent(x), self.model_stab.to_latent(x)), 1
    699     )

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

The problem is pretty strait forward, although I have not had a chance to think about the solution. I'm a little surprised the training even works ... so maybe I'm doing the predictions wrong? It's worth checking out the fairly simple notebook linked above to make sure. AFAICT, The problem is that we're trying to concatenate two 1 dimensional arrays with the "1st" dimension axis, which obviously doesn't exist. We can hack things by casting each of the arrays to be 2 dimensional i.e. `self.model_bind.to_latent(x)` -> `self.model_bind.to_latent(x)[None, :]` This may be the best fix due to the fact that we want the user to specify one or more latent nodes.

**Comment by WSDeWitt** [comment]
Waiting on #170, which should re-enable testing for these models when fixed.
