### ISSUE TITLE
Probable plotting bug

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/torchdms#172]
The boolean indexing in these lines is a self comparison, so either it's not needed, or it was intending to do something else:
https://github.com/matsengrp/torchdms/blob/7003697b61ec4cf759baf9b235c1dc4a353b4b86/torchdms/plot.py#L87-L88

**Comment by jgallowa07** [comment]
This is for removing nulls I believe? otherwise the pearson correlation coeff function get's angry

**Comment by WSDeWitt** [comment]
I see, so do we want `~targ.isnan()` or `targ.isfinite()`?

**Comment by WSDeWitt** [comment]
Just noticed you fixed in #171, thanks!
